function frm = frame(pose)
    %FRAME Returns the frame for a given pose vector
    %   frm = FRAME(pose) returns a 4-by-4 matrix for a 1-by-6 vector
    %       pose(1:3) = [cx, cy, cz] | coordinates of position in mm
    %       pose(4:6) = [ax, ay, az] | angles of orientation in Radians
    
    % Transformation matrix in x, y and z-axes
    T = [ 1 0 0 pose(1); ...
          0 1 0 pose(2) ; ...
          0 0 1 pose(3) ; ...
          0 0 0 1 ];
    
    % Transformation matrix about x-axis
    Rx = [ 1 0 0 0 ; ...
           0 cos(pose(4)) -sin(pose(4)) 0 ; ...
           0 sin(pose(4))  cos(pose(4)) 0 ; ...
           0 0 0 1 ];
      
    % Transformation matrix about y-axis  
    Ry = [ cos(pose(5)) 0 sin(pose(5)) 0 ; ...
           0 1 0 0 ; ...
          -sin(pose(5)) 0 cos(pose(5)) 0 ; ...
           0 0 0 1 ];
    
    % Transformation matrix about z-axis  
    Rz = [ cos(pose(6)) -sin(pose(6)) 0 0 ; ...
           sin(pose(6))  cos(pose(6)) 0 0 ; ...
           0 0 1 0 ; ...
           0 0 0 1 ];
    
    % Combining transformations to the frame matrix 
    frm = T*Rx*Ry*Rz;
    
    end